# Generated by Django 5.0.7 on 2024-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ManyToManyField(to='recruiter.company'),
        ),
    ]
